[google_drive]
credentials = '''
{
  "type": "service_account",
  "project_id": "YOUR_PROJECT_ID_HERE",
  "private_key_id": "YOUR_PRIVATE_KEY_ID_HERE",
  "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n",
  "client_email": "YOUR_SERVICE_ACCOUNT@YOUR_PROJECT.iam.gserviceaccount.com",
  "client_id": "YOUR_CLIENT_ID_HERE",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "YOUR_CLIENT_CERT_URL_HERE"
}
'''

[google_drive.ncert_folders]
grade_6 = "YOUR_GRADE_6_FOLDER_ID"
grade_7 = "YOUR_GRADE_7_FOLDER_ID"
grade_8 = "YOUR_GRADE_8_FOLDER_ID"
grade_9 = "YOUR_GRADE_9_FOLDER_ID"
grade_10 = "YOUR_GRADE_10_FOLDER_ID"

output_folder = "YOUR_OUTPUT_FOLDER_ID"

[sarvam]
api_key = "YOUR_SARVAM_API_KEY_HERE"
