[google_drive]
credentials = '''
{
  "type": "service_account",
  "project_id": "your-project-id-here",
  "private_key_id": "your-private-key-id",
  "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR-ACTUAL-PRIVATE-KEY-HERE\n-----END PRIVATE KEY-----\n",
  "client_email": "math-video-creator@your-project-id.iam.gserviceaccount.com",
  "client_id": "your-client-id",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "your-client-cert-url"
}
'''

[google_drive.ncert_folders]
grade_6 = "your-grade-6-folder-id"
grade_7 = "your-grade-7-folder-id"
grade_8 = "your-grade-8-folder-id"
grade_9 = "your-grade-9-folder-id"
grade_10 = "your-grade-10-folder--id"

output_folder = "your-generated-videos-folder-id"
